fos_elastica:
  clients:
    default:
      host: '%env(ELASTICSEARCH_HOST)%'
      port: '%env(ELASTICSEARCH_PORT)%'
  indexes:
    domains:
      persistence:
        driver: orm
        model: App\Entity\Domain
        provider: ~
        listener:
          insert: true
          update: true
          delete: true
        finder: ~
      properties:
        name: { type: text }
        smtpHost: { type: text }
        smtpUser: { type: text }
        smtpPass: { type: text }
        fromEmail: { type: text }
        fromName: { type: text }
        fromHost: { type: text }
