security:
    # Конфигурация хэширования паролей
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Провайдер пользователей
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Настройка брандмауэров (firewalls)
    firewalls:
        # Отключение безопасности для ресурсов разработки
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Основной брандмауэр
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /admin
            logout:
                path: app_logout
            custom_authenticator: App\Security\AppCustomAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true
            entry_point: form_login

    # Контроль доступа
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

