stimulus:
  # Путь к каталогу с вашими контроллерами
  controller_paths:
    - '%kernel.project_dir%/assets/controllers'
  # Путь к файлу controllers.json
  controllers_json: '%kernel.project_dir%/assets/controllers.json'