controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_domain_search:
     path: /admin/search-domains
     controller: App\Controller\Admin\DomainCrudController::search
     methods: [ GET ]
