controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


#admin_domain_index:
#    path: /admin/domains
#    controller: App\Controller\Admin\DomainCrudController::index
#    methods: [GET]

admin_domain_search:
    path: /admin/search
    controller: App\Controller\Admin\DomainCrudController::search
#admin_domain_search:
 #   path: /admin/search-domains
  #  controller: App\Controller\Admin\DomainCrudController::search
   # methods: [ GET ]
